GET http://localhost:3000/products

###
GET http://localhost:3000/products/67471f9a567ff59e02673443

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"갤럭시 S40",
  "description":"완전 최신",
  "price":2000000,
  "tags":["휴대폰","삼성"]
}

###
PATCH  http://localhost:3000/products/67471f9a567ff59e02673443
Content-Type: application/json

{
  "price":99000
}