GET http://localhost:3000/products

###
GET http://localhost:3000/products/67471f9a567ff59e02673443

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"아이폰 13",
  "description":"4년 써도 멀쩡한 명기",
  "price":990000,
  "tags":["휴대폰","애플"]
}

###
PATCH  http://localhost:3000/products/67471f9a567ff59e02673443
Content-Type: application/json

{
  "price":99000
}